SALES_DATASALES_DATA.PUBLICSALES_DATA-- Create warehouse for data sharing operations
CREATE WAREHOUSE SHARE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE SHARE_WH;

CREATE DATABASE SALES_DATA;

CREATE SCHEMA SALES_DATA.PUBLIC;

-- Create sample table
CREATE TABLE SALES_DATA.PUBLIC.CUSTOMER_ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    AMOUNT DECIMAL(10,2),
    REGION VARCHAR(50)
);

-- Insert sample data
INSERT INTO SALES_DATA.PUBLIC.CUSTOMER_ORDERS VALUES
    (1, 101, '2024-01-15', 5000.00, 'NORTH'),
    (2, 102, '2024-01-16', 7500.00, 'SOUTH'),
    (3, 103, '2024-01-17', 3200.00, 'EAST');


