USE WAREHOUSE SHARE_WH;

CREATE SHARE SALES_SHARE;

GRANT USAGE ON DATABASE SALES_DATA TO SHARE SALES_SHARE;

GRANT USAGE ON SCHEMA SALES_DATA.PUBLIC TO SHARE SALES_SHARE;

GRANT SELECT ON TABLE SALES_DATA.PUBLIC.CUSTOMER_ORDERS TO SHARE SALES_SHARE;

ALTER SHARE SALES_SHARE ADD ACCOUNTS = ZLMNHTD.FITS;

