USE WAREHOUSE COMPUTE_WH;

SHOW GRANTS;

SHOW GRANTS TO SHARE SALES_SHARE;
SHOW GRANTS OF SHARE SALES_SHARE;
SHOW GRANTS ON SHARE SALES_SHARE;

SHOW GRANTS TO ROLE ACCOUNTADMIN;
SHOW GRANTS OF ROLE ACCOUNTADMIN;

SHOW GRANTS TO USER FERNANDOKARNAGI;

SHOW GRANTS ON DATABASE SALES_DATA;