-- Remove specific account from share
ALTER SHARE SALES_SHARE REMOVE ACCOUNTS = ZLMNHTD.FITS;

-- Revoke object grants
REVOKE SELECT ON TABLE SALES_DATA.PUBLIC.CUSTOMER_ORDERS FROM SHARE SALES_SHARE;
REVOKE USAGE ON SCHEMA SALES_DATA.PUBLIC FROM SHARE SALES_SHARE;
REVOKE USAGE ON DATABASE SALES_DATA FROM SHARE SALES_SHARE;

-- Drop the share
DROP SHARE SALES_SHARE;

-- Drop reader account (if needed)
DROP MANAGED ACCOUNT READER_ANALYTICS;

-- Consumer cleanup
DROP DATABASE SHARED_SALES_DATA;