-- View all outbound shares
SHOW SHARES;

-- View share usage by consumers
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
WHERE TARGET_CLOUD = 'SHARE';

-- Monitor reader account costs
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'READER_WH';